version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb-cvl-prod
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo-express-cvl-prod
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=cvl-flower
  springapi:
    image: cvlapi
    container_name: cvl-api-prod
    ports:
      - "8080:8080"
    links:
      - mongodb
  cvlfont:
    image: cvlfront2
    container_name: cvl-front-prod
    volumes:
      - '.:/app'
      - /app/node_modules/
    ports:
      - "8082:4173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=5173"
      - "traefik.http.routers.app.rule=Host(`example.com`)"

volumes:
  data: {}
networks:
  default:
    name: cvl_network